<a href="https://colab.research.google.com/github/baiyinnamula/EasyToUnderstandPandas/blob/main/%E7%AC%AC5%E7%AB%A0Pandas%E9%AB%98%E7%BA%A7%E6%93%8D%E4%BD%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

df = pd.read_excel('https://www.gairuo.com/file/data/dataset/team.xlsx')

## 5.1 复杂查询

### 5.1.1 逻辑运算

In [ ]:
# Q1 成绩大于 35
df.Q1 > 36

In [ ]:
df.index == 1

In [ ]:
# # df.loc[:,'Q1':'Q4']部分只取数字部分，否则会因字符无大于运算而报错
df.loc[:, 'Q1':'Q4'] > 60

In [ ]:
~(df.Q1 < 60) & (df['team'] == 'C')

### 5.1.2 逻辑筛选数据

In [ ]:
df[df['Q1'] == 8]

In [ ]:
df[df.Q1 > df.Q2]

In [ ]:
df[~(df['Q1'] == 8)] # 不等于8

In [ ]:
df[df.name == 'Ben'] # 姓名为Ben

In [ ]:
# 表达式与切片一致
df.loc[df['Q1'] > 90, 'Q1'] # Q1大于90，只显示Q1

In [ ]:
df.loc[(df.Q1 > 80) & (df.Q2 < 15)] # and关系

In [ ]:
df.loc[(df.Q1 > 90) | (df.Q2 < 90)] # or关系

In [ ]:
df.loc[df['Q1'] > 90, 'Q1':] # Q1大于90，显示Q1及其后所有列

In [ ]:
# Q1、Q2成绩全为超过80分的
df[(df.loc[:, ['Q1','Q2']] > 80).all(1)]

In [ ]:
(df.loc[:, ['Q1','Q2']] > 80).all(1)

In [ ]:
# Q1、Q2成绩至少有一个超过80分的
df[(df.loc[:, ['Q1', 'Q2']] > 80).any(1)]

### 5.1.3 函数筛选

In [ ]:
# 查询最大索引的值
df.Q1[lambda s: max(s.index)]

In [ ]:
max(df.Q1.index)

In [ ]:
df.Q1[df.index==99]

In [ ]:
df.loc[:, lambda df: df.columns.str.len()==4] # 由真假值组成的序列

In [ ]:
df.loc[:, lambda df: [i for i in df.columns if 'Q' in i]] # 列名列

In [ ]:
[i for i in df.columns if 'Q' in i]

In [ ]:
df.iloc[:3, lambda df: df.columns.str.len()==2] # 由真假值组成的序列

### 5.1.4 比较函数

In [ ]:
# 以下相当于 df[df.Q1 == 60]
df[df.Q1.eq(60)]

In [ ]:
# df.ne() # 不等于 !=
# df.le() # 小于等于 <=
# df.lt() # 小于 <
# df.ge() # 大于等于 >=
# df.gt() # 大于 >

In [ ]:
df[df.team.isin(['A', 'B'])]

In [ ]:
df[df.isin({'team': ['C', 'D'], 'Q1':[36,93]})]

### 5.1.5 查询df.query()

In [ ]:
df.query('Q1>Q2>90')

In [ ]:
df.query('Q1 + Q2 > 180')

In [ ]:
df.query('Q1 == Q2')

In [ ]:
df.query('(Q1 < 50) & (Q2 > 40) and (Q3>90)')

In [ ]:
df.query('Q1>Q2>Q3>Q4')

In [ ]:
df.query('team != "C"')

In [ ]:
df.query('team not in ("E","A","B")')

In [ ]:
a =df.Q1.mean()
df.query('Q1 > @a + 40')

In [ ]:
df.query('Q1 > Q2 + @a')

In [ ]:
# df.eval()用法与df.query类似
df[df.eval("Q1 > 90 > Q3 > 10")]
df[df.eval("Q1 > `Q2`+@a")]

### 5.1.6 筛选df.filter()

In [ ]:
df.filter(items=['Q1', 'Q2']) # 选择两列

In [ ]:
df.filter(regex='Q', axis=1)  # 列名包含Q的列

In [ ]:
df.filter(regex='e$', axis=1)

In [ ]:
df.filter(regex='1$', axis=0) # 正则，索引名以1结尾

In [ ]:
df.filter(like='2', axis=0)

In [ ]:
df.filter(regex='^2', axis=0).filter(like='Q', axis=1)

### 5.1.7 按数据类型查询

In [ ]:
df.select_dtypes(include=['float64']) # 选择float64型数据

In [ ]:
df.select_dtypes(include='bool')

In [ ]:
df.select_dtypes(include=['number']) # 只取数字型

In [ ]:
df.select_dtypes(exclude=['int']) # 排除int类型

In [ ]:
df.select_dtypes(exclude=['datetime64'])

## 5.2 数据类型转换

### 5.2.1 推断类型

In [ ]:
df.infer_objects() # 推断后的DataFrame

In [ ]:
df.infer_objects().dtypes

In [ ]:
# 推荐这个新方法，它支持string类型
df.convert_dtypes()

In [ ]:
df.convert_dtypes().dtypes

### 5.2.2 指定类型

In [ ]:
m = ['1', 2, 3]
s = pd.to_numeric(m)

In [ ]:
# 按大体类型推定
m = ['1', 2, 3]
s = pd.to_numeric(s) # 转成数字
# pd.to_datetime(m) # 转成时间
# pd.to_timedelta(m) # 转成时间差
# pd.to_datetime(m, errors='coerce') # 错误处理
# pd.to_numeric(m, errors='ignore')
# pd.to_numeric(m, errors='coerce').fillna(0) # 兜底填充
# pd.to_datetime(df[['year', 'month', 'day']]) # 组合成日期

In [ ]:
# 最低期望
pd.to_numeric(m, downcast='integer') # 至少为有符号int数据类型
# array([1, 2, 3], dtype=int8)
pd.to_numeric(m, downcast='signed') # 同上
# array([1, 2, 3], dtype=int8)

In [ ]:
pd.to_numeric(m, downcast='unsigned') # 至少为无符号int数据类型
# array([1, 2, 3], dtype=uint8)
pd.to_numeric(m, downcast='float') # 至少为float浮点类型
# array([1., 2., 3.], dtype=float32)

In [ ]:
df = df.select_dtypes(include='number')
# 应用函数
df.apply(pd.to_numeric)

### 5.2.3 类型转换astype()

In [ ]:
df.Q1.astype('int32').dtypes

In [ ]:
df.astype({'Q1':'int32', 'Q2':'int32'}).dtypes

In [ ]:
df.index.astype('int64')

In [ ]:
#data.rate.apply(lambda x: x.replace('%', '')).astype('float')/100

### 5.2.4 转为时间类型

In [ ]:
t = pd.Series(['20200801', '20200802'])
t

In [ ]:
pd.to_datetime(t)

In [ ]:
t.astype('datetime64[ns]')

## 5.3 数据排序

### 5.3.1 索引排序

In [ ]:
df.sort_index(ascending=False)

In [ ]:
df.sort_index(axis=1, ascending=False)

In [ ]:
df = pd.DataFrame({
'A': [1,2,4],
'B': [3,5,6]
}, index=['a', 'b', 'c'])
df

In [ ]:
# 按要求重新指定索引顺序
df.reindex(['c','b','a'])

In [ ]:
# 指定列顺序
df.reindex(['B','A'], axis=1)

### 5.3.2 数值排序

In [ ]:
df = pd.read_excel('https://www.gairuo.com/file/data/dataset/team.xlsx')

In [ ]:
df.Q1.sort_values()


In [ ]:
df.sort_values('Q4')

In [ ]:
df.sort_values(by=['team','name'], ascending=[True, False])

### 5.3.3 混合排序

In [ ]:
df.reset_index()
df.set_index('name', inplace=True) # 设置name为索引
df.index.names = ['s_name'] # 给索引起名
df.sort_values(by=['s_name','team']) # 排序

In [ ]:
df = pd.read_excel('https://www.gairuo.com/file/data/dataset/team.xlsx')
df.set_index('name').sort_values('team').sort_index()

In [ ]:
df.name.sort_values().index

In [ ]:
# 将新的索引应用到数据中
df.reindex(df.name.sort_values().index)

### 5.3.4 按值大小排序

In [ ]:
# 先按Q1最小在前，如果相同，Q2小的在前
df.nsmallest(5, ['Q1', 'Q2'])

## 5.4 添加修改

### 5.4.1 修改数值

In [ ]:
df.iloc[0, 0]

In [ ]:
df.iloc[0,0] = 'Lily'

In [ ]:
df[df.Q1 < 60] = 60

In [ ]:
df

In [ ]:
v = [1, 3, 5, 7, 9] * 20
v

In [ ]:
df.Q1 = v

In [ ]:
df.Q1

In [ ]:
df.loc[1:3, 'Q1':'Q2']

In [ ]:
# 指定修改的目的数据
df1 = pd.DataFrame({'Q1':[1,2,3],'Q2':[4,5,6]})
df1

In [ ]:
df.loc[1:3,'Q1':'Q2'] = df1

In [ ]:
df.loc[1:3,'Q1':'Q2']

### 5.4.2 替换数据

In [ ]:
s = pd.Series([3,6,0,4,6,10])
s

In [ ]:
s.replace(0, 5)

In [ ]:
# 使用正则表达式
# df.replace(to_replace=r'^ba.$', value='new', regex=True)
# df.replace({'A': r'^ba.$'}, {'A': 'new'}, regex=True)
# df.replace(regex={r'^ba.$': 'new', 'foo': 'xyz'})
# df.replace(regex=[r'^ba.$', 'foo'], value='new')

### 5.4.3 填充空值

In [ ]:
df.fillna(0)

In [ ]:
df.rename(columns={'team':'class'})

In [ ]:
df.rename_axis("test")

In [ ]:
df.rename(index={0:"x",1:"y",2:"z"})

### 5.4.4 修改索引名

### 5.4.5 增加列

In [ ]:
df['total'] = df.Q1 + df.Q2 + df.Q3 + df.Q4

In [ ]:
df['total'] = df.loc[:,'Q1':'Q4'].sum(1)

In [ ]:
df

In [ ]:
df['total'] = df.select_dtypes(include=['int']).sum(1)

In [ ]:
df

In [ ]:
df['total'] = df.loc[:,'Q1':'Q4'].apply(lambda x: sum(x), axis='columns')
df

### 5.4.6 插入列df.insert()

In [ ]:
df.drop('total', axis=1, inplace=True)

In [ ]:
df.insert(2, 'total', df.sum(1))

In [ ]:
df

### 5.4.7 指定列df.assign()

In [ ]:
df.drop('total', axis=1, inplace=True)
df.assign(total = df.sum(1))

In [ ]:
df

In [ ]:
df.assign(total=df.sum(1), Q=100)

In [ ]:
df.assign(total = df.sum(1)).assign(Q=100)

In [ ]:
(df.assign(total = df.sum(1))
.assign(Q=100)
.assign(name_len = df.name.str.len())
.assign(avg=df.mean(1)).assign(avg2=lambda d:d.total/4)
)


### 5.4.8 执行表达式df.eval()

In [ ]:
df.eval('total=Q1+Q2+Q3+Q4')

### 5.4.9 增加行

In [ ]:
df.loc[100] = ['tom','A', 88,88,88,88]

In [ ]:
df

### 5.4.10 追加合并

In [ ]:
df = pd.DataFrame([[1, 2], [3, 4]], columns=list('AB'))
df2 = pd.DataFrame([[5, 6], [7, 8]], columns=list('AB'))

In [ ]:
df

In [ ]:
df2

In [ ]:
df1.append(df2)

In [ ]:
s1 = pd.Series(['a', 'b'])
s2 = pd.Series(['c', 'd'])
pd.concat([s1, s2])
pd.concat([s1, s2], ignore_index=True) # 索引重新编

In [ ]:
# 原数索引不变，增加一个一层索引（keys里的内容），变成多层索引
pd.concat([s1, s2], keys=['s1', 's2'])
pd.concat([s1, s2], keys=['s1', 's2'],
names=['Series name', 'Row ID'])

### 5.4.11 删除

### 5.4.12 删除空值

In [ ]:
df.dropna() # 一行中有一个缺失值就删除
df.dropna(axis='columns') # 只保留全有值的列
df.dropna(how='all') # 行或列全没值才删除
df.dropna(thresh=2) # 至少有两个空值时才删除
df.dropna(inplace=True) # 删除并使替换生效

## 5.5 高级过滤

In [ ]:
df = pd.read_excel('https://www.gairuo.com/file/data/dataset/team.xlsx')
df = df.select_dtypes(include='number')
df

In [ ]:
df.where(df > 70)

In [ ]:
df[df > 70]

In [ ]:
df.where(lambda d: d.Q1>50)

In [ ]:
df.Q1.where(pd.Series([True] * 3))

In [ ]:
df.where(df>=60, '不及格')

In [ ]:
# c 定义一个数是否为偶数的表达式
c = df%2 ==0
df.where(~c, -(df-20))

### 5.5.2 np.where()

In [ ]:
np.where(df>=60, '合格', '不合格')

In [ ]:
# 让df.where()中的条件为假，从而应用np.where()的计算结果
df.where(df==9999999, np.where(df>=60, '合格', '不合格'))

In [ ]:
(
  df.assign(avg=df.mean(1))
  .assign(及格=lambda d: np.where(d.avg>=60, '是','否'))
)

### 5.5.3 df.mask()

In [ ]:
df.mask(df>80, '优秀')

In [ ]:
df = pd.read_excel('https://www.gairuo.com/file/data/dataset/team.xlsx')
# 返回布尔序列，符合条件的行值为True
(df.where((df.team=='A') & (df.Q1>60)) == df).Q1

In [ ]:
# 返回布尔序列，符合条件的行值为False
(df.mask((df.team=='A') & (df.Q1>60)) == df).Q1

In [ ]:
df.mask((df.team=='A') & (df.Q1>60)) == df

### 5.5.4 df.lookup()

In [ ]:
# 行列相同数量，返回一个array
df.lookup([1,3,4], ['Q1','Q2','Q3'])

## 5.6 数据迭代

### 5.6.1 迭代Series

In [ ]:
for i in df.name:
  print(i)

In [ ]:
for i,n,q in zip(df.index, df.name, df.Q1):
  print(i, n ,q)

### 5.6.2 df.iterrows()

In [ ]:
for index, row in df.iterrows():
  print(index, row['name'],row.Q1)

### 5.6.3 df.itertuples()

In [ ]:
for row in df.itertuples():
  print(row.Index, row.name)

### 5.6.4 df.items()

In [ ]:
for label, ser in df.items():
  print(label)
  print(ser[:3], end="\n\n")

### 5.6.5 按列迭代

In [ ]:
for column in df:
  print(column)

In [ ]:
for column in df:
  print(df[column])

## 5.7 函数应用

Pandas提供了几个常用的调用函数的方法。
* pipe()：应用在整个DataFrame或Series上。
* apply()：应用在DataFrame的行或列中，默认为列。
* applymap()：应用在DataFrame的每个元素中。
* map()：应用在Series或DataFrame的一列的每个元素中。

### 5.7.1 pipe()

In [ ]:
# 定义一个函数，给所有季度的成绩加n，然后增加平均数
# 其中n中要加的值为必传参数
def add_mean(rdf, n):
  df = rdf.copy()
  df = df.loc[:,'Q1':'Q4'].applymap(lambda x: x+n)
  df['avg'] = df.loc[:,'Q1':'Q4'].mean(1)
  return df
# 调用
df.pipe(add_mean, 100)

In [ ]:
# 筛选出Q1大于等于80且Q2大于等于90的数据
df.pipe(lambda df_,x,y: df_[(df_.Q1 >=x)& (df_.Q2 >=y)], 80, 90)

### 5.7.2 apply()

In [ ]:
# 将name全部变为小写
df.name.apply(lambda x: x.lower())

In [ ]:
# 去掉一个最高分和一个最低分再算出平均分
def my_mean(s):
  max_min_ser = pd.Series([-s.max(), -s.min()])
  return s.append(max_min_ser).sum()/(s.count()-2)

df.select_dtypes(include='number').apply(my_mean)

In [ ]:
# 同样的算法以学生为维度计算
(
df.set_index('name') # 设定name为索引
.select_dtypes(include='number')
.apply(my_mean, axis=1) # 横向计算
)

In [ ]:
# 函数，将大于90分数标记为good
fun = lambda x: np.where(x.team=='A' and x.Q1>90, 'good' ,'other')
df.apply(fun, axis=1)


In [ ]:
# 同上效果
(df.apply(lambda x: x.team=='A' and x.Q1>90, axis=1).map({True:'good', False:'other'})
)


In [ ]:
df.apply(lambda x: 'good' if x.team=='A' and x.Q1>90 else 'other', axis=1)

### 5.7.3 applymap()

In [ ]:
# 计算数据的长度
def mylen(x):
  return len(str(x))

df.applymap(lambda x:mylen(x))


In [ ]:
df.applymap(mylen)

### 5.7.4 map()

In [ ]:
df.team.map({'A':'一班', 'B':'二班','C':'三班', 'D':'四班','E':'五班'}) # 枚举替换

In [ ]:
df.team

In [ ]:
df.team.map('I an a {}'.format)

In [ ]:
df.team.map('I am a {}'.format, na_action='ignore')

In [ ]:
t = pd.Series({'six': 6., 'seven': 7.})

In [ ]:
# 应用函数
def f(x):
  return len(str(x))
df['name'].map(f)

### 5.7.5 agg()

In [ ]:
df.agg('max')

In [ ]:
df.select_dtypes(include='number').agg(['sum', 'min'])

In [ ]:
# 序列多个聚合
df.agg({'Q1' : ['sum', 'min'], 'Q2' : ['min', 'max']})

In [ ]:
# 分组后聚合
df.groupby('team').agg('max')

In [ ]:
df.Q1.agg(['sum', 'mean'])

In [ ]:
def mymean(x):
  return x.mean() 
df.Q2.agg(['sum', mymean])

In [ ]:
# 每列使用不同的方法进行聚合
df.agg(a=('Q1', max),
  b=('Q2', 'min'),
  c=('Q3', np.mean),
  d=('Q4', lambda s:s.sum()+1)
)


In [ ]:
# 按行聚合
df.loc[:,'Q1':].agg("mean", axis="columns")

In [ ]:
# 利用pd.Series.add方法对所有数据加分，other是add方法的参数
df.loc[:,'Q1':].agg(pd.Series.add, other=10)

### 5.7.6 transform()

In [ ]:
df.transform(lambda x: x*2) # 应用匿名函数

In [ ]:
df.groupby('team').sum()

In [ ]:
df.groupby('team').transform(sum)

### 5.7.7 copy()

## 5.8 本章小结